title: Koichi Nakayamada
description: Personal Blog and Projects
baseurl: ""
url: "https://koichin.com"

permalink: /:categories/:title/


plugins:
  - jekyll-feed

markdown: kramdown

defaults:
  - scope:
      path: "_posts/blog"
    values:
      layout: post
      category: blog

  - scope:
      path: "_posts/project"
    values:
      layout: post
      category: project