title: Koichi Nakayamada
description: Personal Blog and Projects
baseurl: ""
url: "https://koichin.com"

permalink: /:categories/:title/

collections:
  blog:
    output: true
    permalink: /blog/:title/
  project:
    output: true
    permalink: /project/:title/

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM