title: Koichi Nakayamada
description: Personal Blog and Projects
baseurl: "" # Leave blank for local development
url: "https://koichin.com"

permalink: /:categories/:title/

theme: minima

plugins:
  - jekyll-paginate
  - jekyll-feed

markdown: kramdown

include:
  - _posts/blog
exclude:
  - _posts/project

paginate: 10
paginate_path: "/blog/page:num"