title: Koichi Nakayamada
subtitle: Personal Blog and Projects
baseurl: ""
url: "https://koichin.com"

permalink: /:categories/:title/

collections:
  blog:
    output: true
    permalink: /blog/:title/
  project:
    output: true
    permalink: /project/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

include: ["_pages", "404.html"]